### ISSUE TITLE
Determine how we define each region

### ISSUE THREAD

**Issue by aflies1** [promazo/Top-40-2020#9]
We will need to split the country into 5 regions. I have already defined those regions as West, Northwest, Midwest, South, and East. Determine what those lines are so we do not overlap on what universities we want to target per region. As a team decide and define what the lines of each region are. Feel free to think creatively when deciding. The goal of this task is to make sure that there will not be overlap as we continue to the next task. Send your definition od each region to Adam for approval.

**Comment by nick-bennett1** [comment]
We are going to split the country into the 5 traditional regions in the US. The North East, South East, Mid West, South West, and West, instead of having the North west as its own region.

**Comment by preetivenkat** [comment]
https://docs.google.com/spreadsheets/d/14aAQuL2C4nD2GLKvWSjvZm07B2TfVvy3Plnp6MCBM2Y/edit?usp=sharing

**Comment by aflies1** [comment]
Sounds good! We will need to change the region title on the cards for NW
